version: '3.8'

services:
  web-app:
    build: .
    container_name: go_app
    restart: no
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: